// <auto-generated />
using System;
using LibraryManagement.EntityFrameworkDataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LibraryManagement.EntityFrameworkDataAccess.Migrations
{
    [DbContext(typeof(LibraryManagementContext))]
    [Migration("20200308042330_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LibraryManagement.Pocos.BookPoco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BookName")
                        .HasColumnName("Book_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ISBN")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnName("Published_Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("User_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("User_ID");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("LibraryManagement.Pocos.UsersPoco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DOB")
                        .HasColumnName("Date_of_Birth")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnName("User_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LibraryManagement.Pocos.BookPoco", b =>
                {
                    b.HasOne("LibraryManagement.Pocos.UsersPoco", "User")
                        .WithMany("Books")
                        .HasForeignKey("User_ID");
                });
#pragma warning restore 612, 618
        }
    }
}
